name: Daily Commit

on:
  schedule:
    - cron: '30 2 * * *'  # Runs daily at 02:30 UTC
  workflow_dispatch:       # Allows manual triggering

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Fetches all history for proper git operations

      - name: Daily commit step - 23f1002464@ds.study.iitm.ac.in
        run: |
          # Create or update the log file with timestamp
          echo "Daily automated commit - $(date -u)" >> commit-log.txt
          
          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Add, commit, and push
          git add commit-log.txt
          git commit -m "Daily automated commit - $(date -u '+%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
          
          # Push the changes
          git push